name: Update PostgreSQL on Azure

on:
  push:
    branches:
      - main

jobs:
  update_postgresql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get install -y postgresql-client
    
    - name: Get all changed markdown files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        files: |
          **.json
          
    - name: Update PostgreSQL database
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        POSTGRESQL_HOST: ${{ secrets.POSTGRESQL_HOST }}
        POSTGRESQL_PORT: ${{ secrets.POSTGRESQL_PORT }}
        POSTGRESQL_DB: ${{ secrets.POSTGRESQL_DB }}
        POSTGRESQL_USER: ${{ secrets.POSTGRESQL_USER }}
        POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          task_id=$(basename "$file" .json)
          if [ -f "tasks/$file" ]; then
            psql -h $POSTGRESQL_HOST -p $POSTGRESQL_PORT -d $POSTGRESQL_DB -U $POSTGRESQL_USER -c "DELETE FROM tasks WHERE task_id = '$task_id';"
            psql -h $POSTGRESQL_HOST -p $POSTGRESQL_PORT -d $POSTGRESQL_DB -U $POSTGRESQL_USER -c "INSERT INTO tasks (task_id, task_data) VALUES ('$task_id', '$(cat tasks/$file)'::jsonb);"
          else
            psql -h $POSTGRESQL_HOST -p $POSTGRESQL_PORT -d $POSTGRESQL_DB -U $POSTGRESQL_USER -c "DELETE FROM tasks WHERE task_id = '$task_id';"
          fi
        done
