name: Update PostgreSQL on Azure

on:
  push:
    branches:
      - main

jobs:
  update_postgresql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get install -y postgresql-client
        
    - name: Find modified JSON files
      id: find_files
      run: |
        git diff --name-status HEAD^..HEAD | awk '$1 != "D" && $2 ~ /\.json$/ {print $2}' > changed_files.txt
        echo "::set-output name=files::$(cat changed_files.txt)"
        
    - name: Update PostgreSQL database
      if: steps.find_files.outputs.files != ''
      env:
        POSTGRESQL_HOST: ${{ secrets.POSTGRESQL_HOST }}
        POSTGRESQL_PORT: ${{ secrets.POSTGRESQL_PORT }}
        POSTGRESQL_DB: ${{ secrets.POSTGRESQL_DB }}
        POSTGRESQL_USER: ${{ secrets.POSTGRESQL_USER }}
        POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
      run: |
        for file in $(cat changed_files.txt); do
          task_id=$(basename "$file" .json)
          if [ -f "$file" ]; then
            psql -h $POSTGRESQL_HOST -p $POSTGRESQL_PORT -d $POSTGRESQL_DB -U $POSTGRESQL_USER -c "DELETE FROM tasks WHERE task_id = '$task_id';"
            psql -h $POSTGRESQL_HOST -p $POSTGRESQL_PORT -d $POSTGRESQL_DB -U $POSTGRESQL_USER -c "INSERT INTO tasks (task_id, task_data) VALUES ('$task_id', '$(cat $file)'::jsonb);"
          else
            psql -h $POSTGRESQL_HOST -p $POSTGRESQL_PORT -d $POSTGRESQL_DB -U $POSTGRESQL_USER -c "DELETE FROM tasks WHERE task_id = '$task_id';"
          fi
        done
